languageCode = "en-us"
title = "docs.xiv.zone"
theme = "mytheme"
summaryLength = 30
disableHugoGeneratorInject = true
enableEmoji = true
baseURL = "https://docs.xiv.zone/"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
